def remove_space_and_replace_hyphen(districts):
    return [i.replace(' ', '-') for i in districts]


india = [
    {
        "state": "ANDAMAN & NICOBAR ISLANDS",
        "districts": ["Nicobar", "North And Middle Andaman", "South Andaman"],
    },
    {
        "state": "ANDHRA PRADESH",
        "districts": [
            "Ananthapur",
            "Chittoor",
            "Cuddapah",
            "East Godavari",
            "Guntur",
            "Krishna",
            "Kurnool",
            "Nellore",
            "Prakasam",
            "Srikakulam",
            "Visakhapatnam",
            "Vizianagaram",
            "West Godavari",
        ],
    },
    {
        "state": "ARUNACHAL PRADESH",
        "districts": [
            "Changlang",
            "Dibang Valley",
            "East Kameng",
            "East Siang",
            "Kurung Kumey",
            "Lohit",
            "Lower Dibang Valley",
            "Lower Subansiri",
            "Papum Pare",
            "Tawang",
            "Tirap",
            "Upper Siang",
            "Upper Subansiri",
            "West Kameng",
            "West Siang",
        ],
    },
    {
        "state": "ASSAM",
        "districts": [
            "Barpeta",
            "Bongaigaon",
            "Cachar",
            "Darrang",
            "Dhemaji",
            "Dhubri",
            "Dibrugarh",
            "Goalpara",
            "Golaghat",
            "Hailakandi",
            "Jorhat",
            "Kamrup",
            "Karbi Anglong",
            "Karimganj",
            "Kokrajhar",
            "Lakhimpur",
            "Marigaon",
            "Nagaon",
            "Nalbari",
            "North Cachar Hills",
            "Sibsagar",
            "Sonitpur",
            "Tinsukia",
        ],
    },
    {
        "state": "BIHAR",
        "districts": [
            "Arwal",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "Darbhanga",
            "East Champaran",
            "Gaya",
            "Jamui",
            "Jehanabad",
            "Kaimur (Bhabua)",
            "Khagaria",
            "Lakhisarai",
            "Madhubani",
            "Munger",
            "Muzaffarpur",
            "Nalanda",
            "Nawada",
            "Patna",
            "Rohtas",
            "Samastipur",
            "Sheikhpura",
            "Sitamarhi",
            "Supaul",
            "Vaishali",
        ],
    },
    {
        "state": "CHANDIGARH",
        "districts": ["Chandigarh"],
    },
    {
        "state": "CHATTISGARH",
        "districts": [
            "Bastar",
            "Bijapur(CGH)",
            "Bilaspur(CGH)",
            "Dantewada",
            "Dhamtari",
            "Durg",
            "Gariaband",
            "Janjgir-champa",
            "Jashpur",
            "Kanker",
            "Kawardha",
            "Korba",
            "Koriya",
            "Mahasamund",
            "Narayanpur",
            "Raigarh",
            "Raipur",
            "Rajnandgaon",
            "Surguja",
        ],
    },
    {
        "state": "DAMAN & DIU",
        "districts": ["Diu"],
    },
    {
        "state": "DELHI",
        "districts": [
            "Central Delhi",
            "East Delhi",
            "New Delhi",
            "North Delhi",
            "North East Delhi",
            "North West Delhi",
            "South Delhi",
            "South West Delhi",
            "West Delhi",
        ],
    },
    {
        "state": "GOA",
        "districts": ["North Goa", "South Goa"],
    },
    {
        "state": "GUJARAT",
        "districts": [
            "Ahmedabad",
            "Amreli",
            "Anand",
            "Banaskantha",
            "Bharuch",
            "Bhavnagar",
            "Dahod",
            "Gandhi Nagar",
            "Jamnagar",
            "Junagadh",
            "Kachchh",
            "Kheda",
            "Mahesana",
            "Narmada",
            "Navsari",
            "Panch Mahals",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Sabarkantha",
            "Surat",
            "Surendra Nagar",
            "Tapi",
            "The Dangs",
            "Vadodara",
        ],
    },
    {
        "state": "HIMACHAL PRADESH",
        "districts": [
            "Bilaspur (HP)",
            "Hamirpur(HP)",
            "Kangra",
            "Kinnaur",
            "Kullu",
            "Lahul & Spiti",
            "Mandi",
            "Shimla",
            "Sirmaur",
            "Solan",
            "Una",
        ],
    },
    {
        "state": "JAMMU & KASHMIR",
        "districts": [
            "Ananthnag",
            "Bandipur",
            "Baramulla",
            "Budgam",
            "Doda",
            "Jammu",
            "Kargil",
            "Kathua",
            "Kulgam",
            "Kupwara",
            "Leh",
            "Poonch",
            "Pulwama",
            "Rajauri",
            "Reasi",
            "Shopian",
            "Srinagar",
            "Udhampur",
        ],
    },
    {
        "state": "JHARKHAND",
        "districts": [
            "Bokaro",
            "Chatra",
            "Deoghar",
            "Dhanbad",
            "Dumka",
            "East Singhbhum",
            "Garhwa",
            "Giridh",
            "Godda",
            "Gumla",
            "Hazaribag",
            "Jamtara",
            "Khunti",
            "Koderma",
            "Latehar",
            "Lohardaga",
            "Pakur",
            "Palamau",
            "Ramgarh",
            "Ranchi",
            "Sahibganj",
            "Seraikela-kharsawan",
            "Simdega",
            "West Singhbhum",
        ],
    },
    {
        "state": "KARNATAKA",
        "districts": [
            "Bagalkot",
            "Bangalore",
            "Bangalore Rural",
            "Belgaum",
            "Bellary",
            "Bidar",
            "Bijapur(KAR)",
            "Chamrajnagar",
            "Chickmagalur",
            "Chikkaballapur",
            "Chitradurga",
            "Dakshina Kannada",
            "Davangere",
            "Dharwad",
            "Gadag",
            "Gulbarga",
            "Hassan",
            "Haveri",
            "Kodagu",
            "Kolar",
            "Koppal",
            "Mandya",
            "Mysore",
            "Raichur",
            "Ramanagar",
            "Shimoga",
            "Tumkur",
            "Udupi",
            "Uttara Kannada",
            "Yadgir",
        ],
    },
    {
        "state": "KERALA",
        "districts": [
            "Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kannur",
            "Kasargod",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thiruvananthapuram",
            "Thrissur",
            "Wayanad",
        ],
    },
    {
        "state": "LAKSHADWEEP",
        "districts": ["Lakshadweep"],
    },
    {
        "state": "MADHYA PRADESH",
        "districts": [
            "Alirajpur",
            "Anuppur",
            "Ashok Nagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dindori",
            "East Nimar",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa",
            "Khargone",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panna",
            "Raisen",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Satna",
            "Sehore",
            "Seoni",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha",
            "West Nimar",
        ],
    },
    {
        "state": "MAHARASHTRA",
        "districts": [
            "Ahmed Nagar",
            "Akola",
            "Amravati",
            "Aurangabad",
            "Beed",
            "Bhandara",
            "Buldhana",
            "Chandrapur",
            "Dhule",
            "Gadchiroli",
            "Gondia",
            "Hingoli",
            "Jalgaon",
            "Jalna",
            "Kolhapur",
            "Latur",
            "Mumbai",
            "Nagpur",
            "Nanded",
            "Nandurbar",
            "Nashik",
            "Osmanabad",
            "Parbhani",
            "Pune",
            "Raigarh(MH)",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sindhudurg",
            "Solapur",
            "Thane",
            "Wardha",
            "Washim",
            "Yavatmal",
        ],
    },
    {
        "state": "MANIPUR",
        "districts": [
            "Bishnupur",
            "Chandel",
            "Churachandpur",
            "Imphal East",
            "Imphal West",
            "Senapati",
            "Tamenglong",
            "Thoubal",
            "Ukhrul",
        ],
    },
    {
        "state": "MEGHALAYA",
        "districts": [
            "East Garo Hills",
            "East Khasi Hills",
            "Jaintia Hills",
            "Ri Bhoi",
            "South Garo Hills",
            "West Garo Hills",
            "West Khasi Hills",
        ],
    },
    {
        "state": "MIZORAM",
        "districts": [
            "Aizawl",
            "Champhai",
            "Kolasib",
            "Lawngtlai",
            "Lunglei",
            "Mammit",
            "Saiha",
            "Serchhip",
        ],
    },
    {
        "state": "NAGALAND",
        "districts": [
            "Dimapur",
            "Kiphire",
            "Kohima",
            "Longleng",
            "Mokokchung",
            "Mon",
            "Peren",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunhebotto",
        ],
    },
    {
        "state": "ODISHA",
        "districts": [
            "Angul",
            "Balangir",
            "Baleswar",
            "Bargarh",
            "Bhadrak",
            "Boudh",
            "Cuttack",
            "Debagarh",
            "Dhenkanal",
            "Gajapati",
            "Ganjam",
            "Jagatsinghapur",
            "Jajapur",
            "Jharsuguda",
            "Kalahandi",
            "Kandhamal",
            "Kendrapara",
            "Kendujhar",
            "Khorda",
            "Koraput",
            "Malkangiri",
            "Mayurbhanj",
            "Nabarangapur",
            "Nayagarh",
            "Nuapada",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Sonapur",
            "Sundergarh",
        ],
    },
    {
        "state": "PONDICHERRY",
        "districts": ["Karaikal", "Mahe", "Pondicherry"],
    },
    {
        "state": "PUNJAB",
        "districts": [
            "Amritsar",
            "Barnala",
            "Bathinda",
            "Faridkot",
            "Fatehgarh Sahib",
            "Fazilka",
            "Firozpur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Mohali",
            "Muktsar",
            "Nawanshahr",
            "Pathankot",
            "Patiala",
            "Ropar",
            "Rupnagar",
            "Sangrur",
            "Tarn Taran",
        ],
    },
    {
        "state": "RAJASTHAN",
        "districts": [
            "Ajmer",
            "Alwar",
            "Banswara",
            "Baran",
            "Barmer",
            "Bharatpur",
            "Bhilwara",
            "Bikaner",
            "Bundi",
            "Chittorgarh",
            "Churu",
            "Dausa",
            "Dholpur",
            "Dungarpur",
            "Ganganagar",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jalor",
            "Jhalawar",
            "Jhujhunu",
            "Jodhpur",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Rajsamand",
            "Sawai Madhopur",
            "Sikar",
            "Sirohi",
            "Tonk",
            "Udaipur",
        ],
    },
    {
        "state": "SIKKIM",
        "districts": ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
    },
    {
        "state": "TAMIL NADU",
        "districts": [
            "Ariyalur",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kanchipuram",
            "Kanyakumari",
            "Karur",
            "Krishnagiri",
            "Madurai",
            "Nagapattinam",
            "Namakkal",
            "Nilgiris",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Salem",
            "Sivaganga",
            "Thanjavur",
            "Theni",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tiruvallur",
            "Tiruvannamalai",
            "Tiruvarur",
            "Tuticorin",
            "Vellore",
            "Villupuram",
            "Virudhunagar",
        ],
    },
    {
        "state": "TELANGANA",
        "districts": [
            "Adilabad",
            "Hyderabad",
            "K.V.Rangareddy",
            "Karim Nagar",
            "Khammam",
            "Mahabub Nagar",
            "Medak",
            "Nalgonda",
            "Nizamabad",
            "Warangal",
        ],
    },
    {
        "state": "TRIPURA",
        "districts": ["Dhalai", "North Tripura", "South Tripura", "West Tripura"],
    },
    {
        "state": "UTTAR PRADESH",
        "districts": [
            "Agra",
            "Aligarh",
            "Allahabad",
            "Ambedkar Nagar",
            "Auraiya",
            "Azamgarh",
            "Bagpat",
            "Bahraich",
            "Ballia",
            "Balrampur",
            "Banda",
            "Barabanki",
            "Bareilly",
            "Basti",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Chandauli",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Etawah",
            "Faizabad",
            "Farrukhabad",
            "Fatehpur",
            "Firozabad",
            "Gautam Buddha Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Gorakhpur",
            "Hamirpur",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Jyotiba Phule Nagar",
            "Kannauj",
            "Kanpur Dehat",
            "Kanpur Nagar",
            "Kaushambi",
            "Kheri",
            "Kushinagar",
            "Lalitpur",
            "Lucknow",
            "Maharajganj",
            "Mahoba",
            "Mainpuri",
            "Mathura",
            "Mau",
            "Meerut",
            "Mirzapur",
            "Moradabad",
            "Muzaffarnagar",
            "Pilibhit",
            "Pratapgarh",
            "Raebareli",
            "Rampur",
            "Saharanpur",
            "Sant Kabir Nagar",
            "Sant Ravidas Nagar",
            "Shahjahanpur",
            "Shrawasti",
            "Siddharthnagar",
            "Sitapur",
            "Sonbhadra",
            "Sultanpur",
            "Unnao",
            "Varanasi",
        ],
    },
    {
        "state": "UTTARAKHAND",
        "districts": [
            "Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi",
        ],
    },
    {
        "state": "WEST BENGAL",
        "districts": [
            "Bankura",
            "Bardhaman",
            "Birbhum",
            "Cooch Behar",
            "Darjiling",
            "East Midnapore",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Kolkata",
            "Malda",
            "Medinipur",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "North Dinajpur",
            "Puruliya",
            "South 24 Parganas",
            "South Dinajpur",
            "West Midnapore",
        ],
    },
]

for state in india:
    print(state["state"], "=", len(state["districts"]))

